from collections import deque 
d = deque() 
d.append(1) 
d.append(2) 
d.append(3) 
print(d) 
d.appendleft(45) 
print(d) 
d.pop() 
print(d) 
d.popleft() 
print(d)  
d.extend([2,3,4,5])
print(d)
d.extendleft([78,54,23]) 
print(d)
d.rotate(2)
print(d)
d.clear() 
print(d) 